version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: real-time-chat-postgres
    environment:
      POSTGRES_PASSWORD: "realtimechat"
      POSTGRES_USER: "realtimechat"
      POSTGRES_DB: "realtimechat"
    ports:
      - "5432:5432"
    networks:
      - network
  zookeeper:
    image: zookeeper:latest
    container_name: real-time-chat-zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - network
  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    container_name: real-time-chat-kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: real-time-chat-kafka
      KAFKA_ZOOKEEPER_CONNECT: "real-time-chat-zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://real-time-chat-kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    ports:
      - "9092:9092"
    networks:
      - network
  real-time-chat-frontend:
    build: real-time-chat-frontend
    container_name: real-time-chat-frontend
    networks:
      - network
    ports:
      - "3000:3000"

networks:
  # Declare our private network.  We must declare one for the magic
  #   # Docker DNS to work, but otherwise its default settings are fine.
  network: {}