server:
  port: 8081
  signing-key: EEESDX88238JJJJKlllX##@
  access-token-validity: 10000
  stripe-webhook-event: wegjownegnjefnnwefn
  adminPassword: DDDXDDD

spring:
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: com.rlchat.server.service.dto
            add:
              type:
                headers: false
      auto-offset-reset: latest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: localhost:9092

  h2:
    console:
      enabled: true
      path: /h2-console/
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/realtimechat
    username: realtimechat
    password: realtimechat